ALTER TABLE evidence
    ADD COLUMN position VARCHAR(50) NOT NULL DEFAULT 'NEUTRAL';

ALTER TABLE theory
    ADD COLUMN support_score REAL NOT NULL DEFAULT 0,
ADD COLUMN opposition_score REAL NOT NULL DEFAULT 0,
ADD COLUMN controversy_score REAL NOT NULL DEFAULT 0,
ADD COLUMN investigation_status VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
ADD COLUMN debate_verdict VARCHAR(50) NOT NULL DEFAULT 'NOT_ENOUGH_DATA';